export async function preloadTemplates() {
	const templatePaths = [
		// Add paths to "modules/midi-qol/templates"
		"modules/midi-qol/templates/actorOnUseMacrosConfig.hbs",
		"modules/midi-qol/templates/attack-roll.html",
		"modules/midi-qol/templates/bonus-damage-roll.html",
		"modules/midi-qol/templates/damage-results.html",
		"modules/midi-qol/templates/damage-results-player.html",
		// "modules/midi-qol/templates/damage-results-v3.html",
		"modules/midi-qol/templates/damage-roll.html",
		"modules/midi-qol/templates/damage-roll-dialog.hbs",
		"modules/midi-qol/templates/dialog.hbs",
		"modules/midi-qol/templates/hits.html",
		"modules/midi-qol/templates/item-card-buttons.html",
		"modules/midi-qol/templates/item-card.hbs",
		"modules/midi-qol/templates/itemProperties.html",
		"modules/midi-qol/templates/midiPropertiesForm.hbs",
		"modules/midi-qol/templates/other-damage-roll.html",
		"modules/midi-qol/templates/roll.html",
		"modules/midi-qol/templates/roll-base.html",
		"modules/midi-qol/templates/roll-dialog.hbs",
		"modules/midi-qol/templates/rolloptions.html",
		"modules/midi-qol/templates/roll-stats.html",
		"modules/midi-qol/templates/rolloptions.html",
		"modules/midi-qol/templates/saves.html",
		"modules/midi-qol/templates/config/gm.hbs",
		"modules/midi-qol/templates/config/player.hbs",
		"modules/midi-qol/templates/config/workflow.hbs",
		"modules/midi-qol/templates/config/concentration.hbs",
		"modules/midi-qol/templates/config/reactions.hbs",
		"modules/midi-qol/templates/config/misc.hbs",
		"modules/midi-qol/templates/config/mechanics.hbs",
		"modules/midi-qol/templates/config/rules.hbs",
		"modules/midi-qol/templates/config/quick.hbs",
		"modules/midi-qol/templates/config/footer.hbs",
		"modules/midi-qol/templates/targetConfirmationConfig.hbs",
		"modules/midi-qol/templates/targetConfirmation.hbs",
		"modules/midi-qol/templates/tooltip.html",
		"modules/midi-qol/templates/tool-card.html",
		"modules/midi-qol/templates/troubleshooter/summary.hbs",
		"modules/midi-qol/templates/troubleshooter/common.hbs",
		"modules/midi-qol/templates/troubleshooter/problems.hbs",
		"modules/midi-qol/templates/troubleshooter/errors.hbs",
		"modules/midi-qol/templates/troubleshooter/modules.hbs",
		"modules/midi-qol/templates/stats/stats.hbs",
		"modules/midi-qol/templates/stats/config.hbs",
		"modules/midi-qol/templates/sounds/sounds.hbs",
		"modules/midi-qol/templates/sounds/quick.hbs",
		"modules/midi-qol/templates/undo-workflow.hbs"
	];
	return loadTemplates(templatePaths);
}
/*    "modules/midi-qol/templates/saves.html",
	"modules/midi-qol/templates/hits.html",
	"modules/midi-qol/templates/item-card.html",
	"modules/midi-qol/templates/tool-card.html",
	"modules/midi-qol/templates/config.html",
	"modules/midi-qol/templates/damage-results.html",
	"modules/midi-qol/templates/roll-stats.html",
	"modules/midi-qol/templates/damage-results-player.html",
	"modules/midi-qol/templates/targetConfirmation.html",
	// "modules/midi-qol/templates/midiProperties.html"
	"modules/midi-qol/templates/sound-config.html",
	"modules/midi-qol/templates/rollAlternate.html",
	"modules/midi-qol/templates/actorOnUseMacrosConfig.html",
	"modules/midi-qol/templates/dialog.html",
	"modules/midi-qol/templates/rollStatsConfig.html",
	"modules/midi-qol/templates/TargetConfirmationConfig.html",
	"modules/midi-qol/templates/rollStats.html",
	*/ 
